# Generated by Django 4.1.2 on 2022-10-28 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_database', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
