# Generated by Django 4.1.2 on 2022-11-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bg_removal', '0003_post_delete_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identify', models.CharField(default='identify', max_length=20)),
                ('password', models.CharField(default='password', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
