# Generated by Django 4.1.2 on 2022-11-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bg_removal', '0004_accounts_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='age',
            field=models.CharField(default='age', max_length=20),
        ),
        migrations.AddField(
            model_name='accounts',
            name='name',
            field=models.CharField(default='name', max_length=20),
        ),
    ]
